# author of the playbook - Sandeep kumar patel
---
- name: Copy a new "ntp.conf" file into place, backing up the original if it differs from the copied version
  ansible.builtin.copy:
    src: /home/ansible/s.txt
    dest: /home/ansible/backup/s.txt
    owner: ansible
    group: ansible
    mode: '0644'
    backup: yes
